linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US

linters:
  enable:
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - goanalysis_metalinter
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec (gas)
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - prealloc
    - scopelint
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
  disable:
    - funlen
    - godox

issues:
  exclude-use-default: false
